name: \"Hello World\" app CI Script

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Clean previous container
      run: docker stop sessionone-test || true
           docker rm sessionone-test || true
    - name: Build Docker Image for Testing
      run: docker build -t sone-image .
    - name: Run Container in Detached Mode
      run: docker run --name sessionone-test -p 7776:7777 sone-image
    - name: Run Tests
      run: docker exec sessionone-test npm test
    - name: Stop and Remove Container
      if: always()
      run: docker stop sessionone-test && docker rm sessionone-test
